### ISSUE TITLE
Cannot parse configuration

### ISSUE THREAD

**Issue by marcDeSantis** [budjb/grails-rabbitmq-native#76] opened 2016-06-06 19:31 UTC
I've tried configuring this in both application.groovy and application.yml and neither works. The errors I get are:

**With application.groovy**

```
java.lang.ClassCastException: java.lang.String cannot be cast to groovy.lang.Binding
```

This is due to the `binding = '#'` setting in:

```
queues {
        "queue.name" {
            exchange = "wwt.product-catalog.product.creation"
            binding = '#'
        }
    }
```

**With application.yml**

```
ERROR org.springframework.boot.SpringApplication - Application startup failed
com.budjb.rabbitmq.exception.InvalidConfigurationException: exchange type is required
```

This happens even when the exchange type is specific:

```
exchanges:
    exchange.name:
      durable: true
      type: topic
```

**Comment by budjb** [comment] 2016-06-06 19:54
Do you happen to have the rest of the stack trace?

**Comment by theironcook** [comment] 2016-06-07 20:01
I get an error that the "exchange type is required" on startup.

I'm just running the example found in the docs.  Here's my yml:

`rabbitmq:
    connections:
        defaultConnection:
            host: xxx.nt.local
            username: xxx
            password: xxx
    exchanges:
        example.exchange:
            type: topic
    queues:
        example.queue:
            durable: false
            exchange: example.exchange`

`com.budjb.rabbitmq.exception.InvalidConfigurationException: exchange type is required
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.springsource.loaded.ri.ReflectiveInterceptor.jlrConstructorNewInstance(ReflectiveInterceptor.java:1075)
    at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
    at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
    at com.budjb.rabbitmq.queuebuilder.ExchangeProperties.validate(ExchangeProperties.groovy:63)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1212)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
    at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:923)
    at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:906)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:168)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodNSafe(ScriptBytecodeAdapter.java:176)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodNSpreadSafe(ScriptBytecodeAdapter.java:183)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethod0SpreadSafe(ScriptBytecodeAdapter.java:198)
    at com.budjb.rabbitmq.queuebuilder.QueueBuilderImpl.configure(QueueBuilderImpl.groovy:75)
    at com.budjb.rabbitmq.queuebuilder.QueueBuilder$configure.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
    at com.budjb.rabbitmq.RabbitContextImpl.createExchangesAndQueues(RabbitContextImpl.groovy:293)
    at com.budjb.rabbitmq.RabbitContextImpl.start(RabbitContextImpl.groovy:70)
    at com.budjb.rabbitmq.RabbitContext$start$0.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
    at com.budjb.rabbitmq.RabbitContextProxy.start(RabbitContextProxy.groovy:65)
    at com.budjb.rabbitmq.RabbitContext$start$0.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
    at com.budjb.rabbitmq.OnStartupListener.onStartup(OnStartupListener.groovy:30)`

**Comment by theironcook** [comment] 2016-06-07 20:17
I was able to get past this problem but moving from 3.2.0 back down to 3.1.3.

**Comment by theironcook** [comment] 2016-06-08 16:04
I figured out the problem.
The "." in the name of the exchange is screwing up the parser that reads the configuration.

When I replace
`exchanges:
   example.exchange`
with
`exchanges:
   exampleexchange`

the code works correct.

**Comment by budjb** [comment] 2016-06-08 16:07
Would you mind trying `example.exchange` with quotations around it?

**Comment by theironcook** [comment] 2016-06-08 16:17
Does not work:
`exchanges:
        "example.exchange":
            type: topic`

Does not work:
`exchanges:
        'example.exchange':
            type: topic`

Works:
`exchanges:
        example-exchange:
            type: topic`

**Comment by budjb** [comment] 2016-06-08 16:18
Does your config have this on one line as presented above, or is each key placed on a new line?

**Comment by theironcook** [comment] 2016-06-08 16:26
Yes, the yaml file is properly formatted.
The Git code tag messes up my code formatting.  Imagine that the lines are properly tabbed / indented.

```
rabbitmq:
    connections:
        defaultConnection:
            host: xxxl
            username: xxx
            password: xxx
    exchanges:
        example.exchange:
            type: topic
    queues:
        example.queue:
            durable: false
            exchange: example.exchange
```

**Comment by budjb** [comment] 2016-06-24 13:45
I've reproduced the issue related to yml configuration. The `.` character is indeed the issue. Even when quoted, the parser ALWAYS treats that as map notation.

**Comment by budjb** [comment] 2016-06-24 16:46
@theironcook I had to refactor the configuration formatting to get this working, unfortunately. I've released 3.3.0 with the changes. Please see the docs for the updated configuration.

Tests are written that ensure periods are acceptable as queue and exchange names with the new code.

**Comment by budjb** [comment] 2016-06-24 16:47
@marcDeSantis The 3.3.0 release should also fix your issues when using the YAML configuration. I haven't been able to reproduce the groovy configuration problem yet, but I'm still working on it.

**Comment by theironcook** [comment] 2016-07-26 19:09
Thank you!

**Comment by theironcook** [comment] 2016-07-26 19:45
UPDATE: Never mind.  I didn't realize Grails dependencies could be straight Jar files.   I moved my "compile: '..." statement into the dependencies { } block in the BuildConfig.groovy file.

I'm a bit confused how I actually get/use the new 3.3.0 release.  Apparently, rabbitmq-native is no longer hosted under https://repo.grails.org/grails/plugins/org/grails/plugins/rabbitmq-native/ but instead it's now under https://repo.grails.org/grails/core/org/grails/plugins/rabbitmq-native/3.3.0/

I've got a grails 2.5.4 application. 
I've updated the BuildConfig.groovy file to have the following entries: 
repositories { ...
  mavenRepo "https://repo.grails.org/grails/core"

plugins { ...
  compile 'org.grails.plugins:rabbitmq-native:3.3.0'

When I run a grails refresh-dependencies command I can see the following messages:
...
|Downloading: org/grails/plugins/rabbitmq-native/3.3.0/rabbitmq-native-3.3.0.pom
|Downloading: com/rabbitmq/amqp-client/3.6.1/amqp-client-3.6.1.pom
|Downloading: com/rabbitmq/amqp-client/3.6.1/amqp-client-3.6.1.jar
Error |
Resolve error obtaining dependencies: Could not find artifact org.grails.plugins:rabbitmq-native:zip:3.3.0 in repo_grails_org_grails_core (https://repo.grails.org/grails/core) (Use --stacktrace to see the full trace)
...

The code is looking for a .zip file but can't find it.  I can see that rabbitmq-native:3.3.0 is deployed as a jar file and there is no .zip file.

Can you tell me what I'm doing wrong and what's going on?
Thanks,

**Comment by budjb** [comment] 2016-07-26 19:53
The latest version for Grails 2.x is 3.1.3. You can find the documentation
here: http://budjb.github.io/grails-rabbitmq-native/2.x/latest/

Any version of the plugin greater than 3.1.x will be Grails 3.x only.

**Comment by budjb** [comment] 2016-07-26 19:57
@theironcook I'm confused. If you're using Grails 2.5, you shouldn't even be using yml configuration anyway, since that's a Grails 3 feature. Have you perhaps gotten the Grails versions mixed up? Am I misunderstanding something?

**Comment by theironcook** [comment] 2016-07-26 20:36
:) @budjb 
I'm juggling a few projects.  I have a Grails 2.5.4 app, a Grails 3.1.7 app (and also a Spring Boot app).  Original questions were regarding 3.1.7 and the latest confusion was regarding a 2.5.4 app.  I'm going to use rabbit-native 3.1.3 (with the unfortunate "." parsing bug) for my Grails 2.5.4 app.

**Comment by budjb** [comment] 2016-11-28 16:52
Are you still having trouble with this?

**Comment by budjb** [comment] 2017-08-18 16:08
Haven't gotten a response so closing this. Reopen if you're still having problems.

**Closed as completed by budjb** 2017-08-18 16:08 UTC
