### ISSUE TITLE
Pending messages not processed on consumer start

### ISSUE THREAD

**Issue by robertoschwald** [budjb/grails-rabbitmq-native#46] opened 2015-01-28 16:15 UTC
I'm new to RabbitMQ and face an issue on processing pending messages in a queue when starting a consumer. Only new messages are processed by the consumer, but pending messages already in the queue on start of the consumer are ignored.

Possibly a config problem on my side.

This is a microservice application architecture.
The main application configures rabbitmq exchanges and queues and a microservice application consumes messages for a specific queue topic ('g.m.msg.entry.new') send by the main application.
I expect that messages already in queue "entryQueue" are picked up by the subscribed consumer on start, but as written, this does not happen.

Main Application rabbitmq-native (2.0.10) config:

    rabbitmq {
        connection = {
                connection host: "localhost", username: 'xxx', password: 'yyy'
        }
        queues = {
            exchange name: 'messageExchange', type: "topic", durable: true, autoDelete: false, {
                 queue name: 'messageQueue', binding: 'g.m.msg', type:topic, durable: true
                 queue name: 'entryQueue', binding: 'g.m.msg.entry.#', type:topic, durable: true
                 queue name: 'logQueue', binding: '#', type:topic, durable: true
            }
            // dead letter exchange keeps all rejected messages
            exchange name: 'deadLetterExchange', type: direct, durable:true, autoDelete:false, {
                queue name: 'deadLetterQueue', durable:true, arguments:["x-dead-letter-exchange":"deadLetterExchange"]
            }
        }
    }

Consumer application Config.groovy:

    rabbitmq {
        connection = {
            connection host: "localhost", username: 'xxx', password: 'yyy', automaticReconnect: true
        }
    }

Consumer:

    class EntryConsumer {
        static rabbitConfig = [
            "exchange":'messageExchange',
            "binding": 'g.m.msg.entry.new',
            "retry": false,
            "autoAck": AutoAck.POST
        ]
        void handleMessage(def body, MessageContext context) {
                ...
        }
    }

When messages are pending in the entryQueue and I start the consumer application, the logs just state:

    DEBUG com.budjb.rabbitmq.RabbitConsumer  - registering consumer 'EntryConsumer' on connection '24c0235d-81a2-46b8-bca7-0f10b87576a3' as a RabbitMQ subscriber

...and nothing is processed by the consumer. As soon as I send a new message on the queue, it is processed as expected, but all pending messages remain on the queue.

Any idea?

**Comment by budjb** [comment] 2015-01-28 16:28
The root of the problem is in the consumer configuration.  If you define a consumer with an exchange and binding, a temporary queue is actually created for that consumer that is destroyed when the application terminates.  This is why new messages are being processed and queued messages are not.  Since the consumer is only consuming from a new temporary queue, messages are actually still queueing up in the queue you actually wanted to consume.  Try this instead:

```
static rabbitConfig = [
    'queue': 'entryQueue'
    'autoAck': AutoAck.POST
]
```
I note that you do not have a queue bound with the same topic key, so you may have to add another queue definition in your config file.

A couple notes about your implementation.
* You do not need to specify the ```type``` in the queue configuration.  Queues do not have an exchange type; they are only a message queue with an optional binding to an exchange.
* While you can define the queues wherever you want, I typically define the queues in the application where I will be consuming those queues.  Since publishers that publish to an exchange do not care about what queue it gets delivered to (that's the job of the binding), I keep queue definitions out of the application that publishes, and define the queue (and binding) in the application consuming those queues.

Let me know if this helps!

**Comment by robertoschwald** [comment] 2015-01-28 17:17
Thanks bud for you quick response!

I changed the consumers to subscribe to queues and now it works. With this, I needed to define a queue per topic, as using queues and bindings on them in consumers seems not to work as I thought (I now read in your documentation for bindings that they are ignored for queues).

A bit more config work than I thought, but if thats the way to go, fine.

BTW: The consumers seem to be started before bootstrap has finished, so better not drop old data in BootStrap.groovy, as new gorm entities might already be created by the consumers...

**Comment by budjb** [comment] 2015-01-28 17:40
Consumers are started during the bootstrap phase.  One of the reasons I wrote this plugin to begin with was that the official RabbitMQ plugin started before even the bootstrap phase.  I haven't figure out a way to hook into the startup process after bootstrap, so it's the best solution I could come up with.

The unfortunate issue is that we have no guarantee of bootstrap order.

I'm going to close this.  Let me know if you need anything else!

**Closed by budjb** 2015-01-28 17:40 UTC

**Comment by budjb** [comment] 2015-03-13 17:34
I'm not sure why I didn't mention this earlier, but there is a way to delay startup of the consumers to allow you to start them when you're ready.  In the grails config, do something like:

```
rabbitmq {
    autoStart = false
}
```

Then, in your Bootstrap (where you do some GORM work), do something like:
```
class BootStrap {
    RabbitContext rabbitContext

    def init = { servletContext ->
        // ... do some GORM work
        rabbitContext.startConsumers()
    }
```

Doing this will guarantee you're able to do any work before incoming messages have an opportunity to create a race condition.

**Comment by robertoschwald** [comment] 2015-03-13 17:41
Great! Thanks for the info.
